---
apiVersion: v1
kind: Pod
metadata:
  name: readonly-nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        readOnlyRootFilesystem: true
      ports:
        - containerPort: 80
